version: "3"
services:
  mongo_manager:
    image: mongo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    networks:
      - mongo
networks:
  mongo:
